version: '3'

services:
  app:
    build: .
    container_name: 'tenmado-api'
    volumes:
      - ./app:/usr/src/app
    ports:
      - "7001:8080"
    environment:
      _ENV: "local"
      GOOGLE_APPLICATION_CREDENTIALS: ".gcp_key/tenmado-24f4299b6aa2.json"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080